// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as DocumentRe from "bs-webapi/src/dom/nodes/DocumentRe.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function appendChild(child, target, param) {
  var match = DocumentRe.asHtmlDocument(document);
  if (match !== undefined) {
    if (target !== undefined) {
      return Caml_option.valFromOption(target).appendChild(child), /* () */0;
    } else {
      var __x = Caml_option.valFromOption(match).body;
      return Belt_Option.map((__x == null) ? undefined : Caml_option.some(__x), (function (body) {
                    body.appendChild(child);
                    return /* () */0;
                  }));
    }
  }
  
}

export {
  appendChild ,
  
}
/* DocumentRe Not a pure module */
