// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as $$String from "bs-platform/lib/es6/string.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Utils$ReasonPlayground from "./utils.bs.js";

var items = /* :: */[
  /* record */[
    /* name */"one",
    /* id */1
  ],
  /* :: */[
    /* record */[
      /* name */"two",
      /* id */2
    ],
    /* [] */0
  ]
];

var __x = Utils$ReasonPlayground.find((function (i) {
        return i[/* name */0] === "onee";
      }), items);

var __x$1 = Belt_Option.map(__x, (function (value) {
        return $$String.uppercase(value[/* name */0]);
      }));

console.log(Belt_Option.getWithDefault(__x$1, "not found"));

var match = Utils$ReasonPlayground.find((function (i) {
        return i[/* name */0] === "onee";
      }), items);

console.log(match !== undefined ? $$String.uppercase(match[/* name */0]) : "oops");

var mapping = /* () */0;

var pmatching = /* () */0;

export {
  items ,
  mapping ,
  pmatching ,
  
}
/*  Not a pure module */
